// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szwtdyfhggfgnnmqpjit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6d3RkeWZoZ2dmZ25ubXFwaml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE1MjUzMzQsImV4cCI6MjEwNzEwMTMzNH0.cGY2Jqu1O2ZHLxmJa5d378pRTjXnW_0yt2nwOZMnj9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});