// AUTO-GENERATED by Database/generate_districts.py
// Sources: IMD District-wise Daily Rainfall (2026), NCDC WB Dengue Outbreak Records, WHO Malaria Incidence (India 2024)
// Generated: 2026-10-09 16:34 IST
// Real rainfall backing: 25/30 districts
// NOTE: Risk scores are computed from real IMD rainfall data + dengue outbreak records + malaria incidence.
//       Fields without a live API (e.g. AQI, animal, satellite) are modelled from rainfall anomalies.

export type Level = "Low" | "Moderate" | "High" | "Critical";
export type Layer =
  | "overall" | "human" | "animal" | "environment"
  | "vector" | "water" | "respiratory" | "zoonotic";

export const LAYERS: { id: Layer; label: string }[] = [
  { id: "overall", label: "Overall Risk" },
  { id: "human", label: "Human Health" },
  { id: "animal", label: "Animal Health" },
  { id: "environment", label: "Environment" },
  { id: "vector", label: "Vector-borne" },
  { id: "water", label: "Water-borne" },
  { id: "respiratory", label: "Respiratory" },
  { id: "zoonotic", label: "Zoonotic" },
];

export interface Contribution { factor: string; value: number }
export interface District {
  id: string; name: string; state: string; lat: number; lng: number;
  population: number; density: number;
  scores: Record<Layer, number>;
  confidence: number;
  why: Contribution[];
  human: { label: string; value: string; delta: number }[];
  animal: { label: string; value: string; delta: number }[];
  environment: { label: string; value: string; delta: number }[];
  weather: { temp: number; humidity: number; rain7d: number; forecast: string };
  satellite: { ndwi: number; floodExtent: number; ndvi: number; lst: number };
  events: string[];
  actions: string[];
  dataSource: string;
}

export function level(score: number): Level {
  if (score >= 75) return "Critical";
  if (score >= 55) return "High";
  if (score >= 35) return "Moderate";
  return "Low";
}

export const districts: District[] = [
  {
    id: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    lat: 22.57,
    lng: 88.36,
    population: 4500000,
    density: 24252,
    confidence: 68,
    scores: {
      overall: 29, human: 21, animal: 28,
      environment: 64, vector: 25, water: 24,
      respiratory: 38, zoonotic: 23,
    },
    why: [ { factor: "Rainfall (7d: 56.5mm)", value: 6 }, { factor: "Vector breeding conditions", value: 5 }, { factor: "Waterlogging / flood risk", value: 4 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 12 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "212", delta: 6 },
      { label: "Diarrhoeal cases (7d)", value: "80", delta: 4 },
      { label: "OPD respiratory visits", value: "314", delta: 2 },
      { label: "Lab-confirmed dengue", value: "14", delta: 4 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "19", delta: 3 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "32", delta: 2 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "48", delta: 5 },
      { label: "Water quality (coliform+)", value: "6% samples", delta: 2 },
      { label: "AQI (PM2.5)", value: "108", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 79,
      rain7d: 56.5, forecast: "Moderate rain expected; watch for waterlogging",
    },
    satellite: {
      ndwi: 0.3, floodExtent: 8.2,
      ndvi: 0.47, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak", "Durga Puja mass gatherings (Oct)", "Pandal water storage risk" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "north-24-parganas",
    name: "North 24 Parganas",
    state: "West Bengal",
    lat: 22.86,
    lng: 88.54,
    population: 10000000,
    density: 2445,
    confidence: 69,
    scores: {
      overall: 73, human: 65, animal: 73,
      environment: 58, vector: 88, water: 83,
      respiratory: 39, zoonotic: 69,
    },
    why: [ { factor: "Rainfall (7d: 62.9mm)", value: 20 }, { factor: "Vector breeding conditions", value: 19 }, { factor: "Waterlogging / flood risk", value: 16 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "459", delta: 19 },
      { label: "Diarrhoeal cases (7d)", value: "228", delta: 16 },
      { label: "OPD respiratory visits", value: "317", delta: 2 },
      { label: "Lab-confirmed dengue", value: "31", delta: 15 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "37", delta: 12 },
      { label: "Poultry mortality events", value: "3", delta: 4 },
      { label: "Stray dog bite reports", value: "59", delta: 7 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "166", delta: 18 },
      { label: "Water quality (coliform+)", value: "21% samples", delta: 8 },
      { label: "AQI (PM2.5)", value: "64", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 82,
      rain7d: 62.9, forecast: "Moderate rain expected; watch for waterlogging",
    },
    satellite: {
      ndwi: 0.32, floodExtent: 0.9,
      ndvi: 0.52, lst: 25,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs", "Issue public advisory on stagnant water and mosquito protection", "Coordinate veterinary checks in peri-urban livestock clusters", "Pre-position ORS, test kits and IV fluids at district hospitals" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "nadia",
    name: "Nadia",
    state: "West Bengal",
    lat: 23.47,
    lng: 88.55,
    population: 5200000,
    density: 1316,
    confidence: 75,
    scores: {
      overall: 13, human: 13, animal: 16,
      environment: 14, vector: 20, water: 5,
      respiratory: 73, zoonotic: 10,
    },
    why: [ { factor: "Rainfall (7d: 4.4mm)", value: 1 }, { factor: "Vector breeding conditions", value: 4 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 10 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "123", delta: 3 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "419", delta: 7 },
      { label: "Lab-confirmed dengue", value: "1066", delta: 3 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "14", delta: 1 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "25", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 56,
      rain7d: 4.4, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.12, floodExtent: 0.0,
      ndvi: 0.2, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "howrah",
    name: "Howrah",
    state: "West Bengal",
    lat: 22.58,
    lng: 88.31,
    population: 4800000,
    density: 2984,
    confidence: 75,
    scores: {
      overall: 8, human: 6, animal: 13,
      environment: 15, vector: 5, water: 5,
      respiratory: 73, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 4.8mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "95", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "419", delta: 7 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "65", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 56,
      rain7d: 4.8, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.12, floodExtent: 0.1,
      ndvi: 0.2, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "hooghly",
    name: "Hooghly",
    state: "West Bengal",
    lat: 22.9,
    lng: 88.39,
    population: 5500000,
    density: 1753,
    confidence: 45,
    scores: {
      overall: 12, human: 6, animal: 13,
      environment: 46, vector: 5, water: 5,
      respiratory: 32, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "117", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "296", delta: 1 },
      { label: "Lab-confirmed dengue", value: "7", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "63", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 57,
      rain7d: 0.0, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.26, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "Modelled (no direct rainfall record)",
  },
  {
    id: "south-24-parganas",
    name: "South 24 Parganas",
    state: "West Bengal",
    lat: 22.24,
    lng: 88.41,
    population: 8199999,
    density: 819,
    confidence: 74,
    scores: {
      overall: 10, human: 9, animal: 16,
      environment: 15, vector: 8, water: 8,
      respiratory: 73, zoonotic: 11,
    },
    why: [ { factor: "Rainfall (7d: 9.2mm)", value: 2 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "106", delta: 2 },
      { label: "Diarrhoeal cases (7d)", value: "40", delta: 1 },
      { label: "OPD respiratory visits", value: "419", delta: 7 },
      { label: "Lab-confirmed dengue", value: "6", delta: 1 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "14", delta: 1 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "25", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "16", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 58,
      rain7d: 9.2, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.13, floodExtent: 0.0,
      ndvi: 0.22, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "murshidabad",
    name: "Murshidabad",
    state: "West Bengal",
    lat: 24.18,
    lng: 88.27,
    population: 7100000,
    density: 1334,
    confidence: 72,
    scores: {
      overall: 22, human: 19, animal: 26,
      environment: 26, vector: 23, water: 22,
      respiratory: 69, zoonotic: 21,
    },
    why: [ { factor: "Rainfall (7d: 17.7mm)", value: 5 }, { factor: "Vector breeding conditions", value: 5 }, { factor: "Waterlogging / flood risk", value: 4 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "173", delta: 5 },
      { label: "Diarrhoeal cases (7d)", value: "75", delta: 4 },
      { label: "OPD respiratory visits", value: "407", delta: 7 },
      { label: "Lab-confirmed dengue", value: "11", delta: 4 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "18", delta: 3 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "31", delta: 2 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "44", delta: 4 },
      { label: "Water quality (coliform+)", value: "6% samples", delta: 2 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 62,
      rain7d: 17.7, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.16, floodExtent: 0.1,
      ndvi: 0.27, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "birbhum",
    name: "Birbhum",
    state: "West Bengal",
    lat: 23.9,
    lng: 87.53,
    population: 3500000,
    density: 771,
    confidence: 73,
    scores: {
      overall: 9, human: 6, animal: 13,
      environment: 25, vector: 5, water: 5,
      respiratory: 71, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 12.4mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "100", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "413", delta: 7 },
      { label: "Lab-confirmed dengue", value: "6", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 59,
      rain7d: 12.4, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.14, floodExtent: 0.1,
      ndvi: 0.24, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "bankura",
    name: "Bankura",
    state: "West Bengal",
    lat: 23.23,
    lng: 87.07,
    population: 3600000,
    density: 523,
    confidence: 73,
    scores: {
      overall: 9, human: 6, animal: 13,
      environment: 24, vector: 5, water: 5,
      respiratory: 71, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 11.9mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "100", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "413", delta: 7 },
      { label: "Lab-confirmed dengue", value: "6", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 59,
      rain7d: 11.9, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.14, floodExtent: 0.0,
      ndvi: 0.24, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "purulia",
    name: "Purulia",
    state: "West Bengal",
    lat: 23.33,
    lng: 86.36,
    population: 2900000,
    density: 469,
    confidence: 74,
    scores: {
      overall: 13, human: 11, animal: 19,
      environment: 20, vector: 12, water: 12,
      respiratory: 71, zoonotic: 14,
    },
    why: [ { factor: "Rainfall (7d: 9.8mm)", value: 3 }, { factor: "Vector breeding conditions", value: 2 }, { factor: "Waterlogging / flood risk", value: 2 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "123", delta: 3 },
      { label: "Diarrhoeal cases (7d)", value: "50", delta: 2 },
      { label: "OPD respiratory visits", value: "413", delta: 7 },
      { label: "Lab-confirmed dengue", value: "7", delta: 2 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "16", delta: 1 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "26", delta: 1 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "24", delta: 2 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 1 },
      { label: "AQI (PM2.5)", value: "60", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 58,
      rain7d: 9.8, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.14, floodExtent: 0.0,
      ndvi: 0.23, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "malda",
    name: "Malda",
    state: "West Bengal",
    lat: 25.0,
    lng: 88.14,
    population: 3900000,
    density: 1072,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.2mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 54,
      rain7d: 0.2, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "jalpaiguri",
    name: "Jalpaiguri",
    state: "West Bengal",
    lat: 26.54,
    lng: 88.72,
    population: 3900000,
    density: 613,
    confidence: 70,
    scores: {
      overall: 80, human: 71, animal: 81,
      environment: 61, vector: 95, water: 95,
      respiratory: 45, zoonotic: 77,
    },
    why: [ { factor: "Rainfall (7d: 109.7mm)", value: 23 }, { factor: "Vector breeding conditions", value: 20 }, { factor: "Waterlogging / flood risk", value: 19 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "498", delta: 21 },
      { label: "Diarrhoeal cases (7d)", value: "258", delta: 19 },
      { label: "OPD respiratory visits", value: "335", delta: 3 },
      { label: "Lab-confirmed dengue", value: "34", delta: 17 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "40", delta: 14 },
      { label: "Poultry mortality events", value: "4", delta: 5 },
      { label: "Stray dog bite reports", value: "64", delta: 8 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "190", delta: 20 },
      { label: "Water quality (coliform+)", value: "24% samples", delta: 9 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 98,
      rain7d: 109.7, forecast: "Heavy rain / flooding risk - next 72h active",
    },
    satellite: {
      ndwi: 0.49, floodExtent: 0.4,
      ndvi: 0.7, lst: 24,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs", "Issue public advisory on stagnant water and mosquito protection", "Coordinate veterinary checks in peri-urban livestock clusters", "Pre-position ORS, test kits and IV fluids at district hospitals" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    lat: 27.04,
    lng: 88.26,
    population: 1800000,
    density: 490,
    confidence: 69,
    scores: {
      overall: 52, human: 46, animal: 54,
      environment: 45, vector: 61, water: 58,
      respiratory: 39, zoonotic: 50,
    },
    why: [ { factor: "Rainfall (7d: 63.0mm)", value: 14 }, { factor: "Vector breeding conditions", value: 13 }, { factor: "Waterlogging / flood risk", value: 11 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "341", delta: 13 },
      { label: "Diarrhoeal cases (7d)", value: "165", delta: 11 },
      { label: "OPD respiratory visits", value: "317", delta: 2 },
      { label: "Lab-confirmed dengue", value: "23", delta: 10 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "30", delta: 8 },
      { label: "Poultry mortality events", value: "2", delta: 3 },
      { label: "Stray dog bite reports", value: "47", delta: 5 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "116", delta: 12 },
      { label: "Water quality (coliform+)", value: "14% samples", delta: 5 },
      { label: "AQI (PM2.5)", value: "60", delta: 0 },
    ],
    weather: {
      temp: 24, humidity: 81,
      rain7d: 63.0, forecast: "Moderate rain expected; watch for waterlogging",
    },
    satellite: {
      ndwi: 0.32, floodExtent: 0.2,
      ndvi: 0.49, lst: 28,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs", "Issue public advisory on stagnant water and mosquito protection" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "uttar-dinajpur",
    name: "Uttar Dinajpur",
    state: "West Bengal",
    lat: 26.1,
    lng: 88.17,
    population: 3000000,
    density: 902,
    confidence: 76,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 75, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "425", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 54,
      rain7d: 0.0, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "dakshin-dinajpur",
    name: "Dakshin Dinajpur",
    state: "West Bengal",
    lat: 25.27,
    lng: 88.77,
    population: 1700000,
    density: 813,
    confidence: 45,
    scores: {
      overall: 12, human: 6, animal: 13,
      environment: 46, vector: 5, water: 5,
      respiratory: 32, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "117", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "296", delta: 1 },
      { label: "Lab-confirmed dengue", value: "7", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 57,
      rain7d: 0.0, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.26, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "Modelled (no direct rainfall record)",
  },
  {
    id: "purba-medinipur",
    name: "Purba Medinipur",
    state: "West Bengal",
    lat: 22.43,
    lng: 87.84,
    population: 5100000,
    density: 1076,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.4mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 9 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "464", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 54,
      rain7d: 0.4, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "paschim-medinipur",
    name: "Paschim Medinipur",
    state: "West Bengal",
    lat: 22.78,
    lng: 87.14,
    population: 5900000,
    density: 613,
    confidence: 45,
    scores: {
      overall: 12, human: 6, animal: 13,
      environment: 46, vector: 5, water: 5,
      respiratory: 32, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "117", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "296", delta: 1 },
      { label: "Lab-confirmed dengue", value: "7", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 57,
      rain7d: 0.0, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.26, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "Modelled (no direct rainfall record)",
  },
  {
    id: "jhargram",
    name: "Jhargram",
    state: "West Bengal",
    lat: 22.46,
    lng: 86.98,
    population: 1100000,
    density: 307,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 12, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 2.7mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "60", delta: 0 },
    ],
    weather: {
      temp: 26, humidity: 55,
      rain7d: 2.7, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.11, floodExtent: 0.0,
      ndvi: 0.18, lst: 30,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "alipurduar",
    name: "Alipurduar",
    state: "West Bengal",
    lat: 26.49,
    lng: 89.52,
    population: 1500000,
    density: 456,
    confidence: 45,
    scores: {
      overall: 12, human: 6, animal: 13,
      environment: 46, vector: 5, water: 5,
      respiratory: 32, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "117", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "296", delta: 1 },
      { label: "Lab-confirmed dengue", value: "7", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "60", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 57,
      rain7d: 0.0, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.26, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "Modelled (no direct rainfall record)",
  },
  {
    id: "kalimpong",
    name: "Kalimpong",
    state: "West Bengal",
    lat: 27.07,
    lng: 88.47,
    population: 250000,
    density: 224,
    confidence: 72,
    scores: {
      overall: 32, human: 28, animal: 35,
      environment: 29, vector: 36, water: 34,
      respiratory: 67, zoonotic: 31,
    },
    why: [ { factor: "Rainfall (7d: 30.7mm)", value: 8 }, { factor: "Vector breeding conditions", value: 7 }, { factor: "Waterlogging / flood risk", value: 6 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "229", delta: 8 },
      { label: "Diarrhoeal cases (7d)", value: "105", delta: 6 },
      { label: "OPD respiratory visits", value: "401", delta: 7 },
      { label: "Lab-confirmed dengue", value: "15", delta: 6 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "22", delta: 5 },
      { label: "Poultry mortality events", value: "2", delta: 1 },
      { label: "Stray dog bite reports", value: "36", delta: 3 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "68", delta: 7 },
      { label: "Water quality (coliform+)", value: "8% samples", delta: 3 },
      { label: "AQI (PM2.5)", value: "60", delta: 0 },
    ],
    weather: {
      temp: 24, humidity: 67,
      rain7d: 30.7, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.21, floodExtent: 0.0,
      ndvi: 0.33, lst: 28,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    lat: 19.08,
    lng: 72.88,
    population: 12400000,
    density: 20694,
    confidence: 76,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 75, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 10 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "425", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "101", delta: 0 },
    ],
    weather: {
      temp: 28, humidity: 54,
      rain7d: 0.0, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 32,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "delhi",
    name: "New Delhi",
    state: "Delhi",
    lat: 28.61,
    lng: 77.21,
    population: 16800000,
    density: 11320,
    confidence: 45,
    scores: {
      overall: 12, human: 6, animal: 13,
      environment: 46, vector: 5, water: 5,
      respiratory: 32, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 5 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "117", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "296", delta: 1 },
      { label: "Lab-confirmed dengue", value: "7", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "82", delta: 0 },
    ],
    weather: {
      temp: 24, humidity: 57,
      rain7d: 0.0, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.26, lst: 28,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "Modelled (no direct rainfall record)",
  },
  {
    id: "guwahati",
    name: "Kamrup Metro (Guwahati)",
    state: "Assam",
    lat: 26.14,
    lng: 91.74,
    population: 1300000,
    density: 1313,
    confidence: 70,
    scores: {
      overall: 13, human: 9, animal: 16,
      environment: 35, vector: 9, water: 9,
      respiratory: 65, zoonotic: 11,
    },
    why: [ { factor: "Rainfall (7d: 29.4mm)", value: 2 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "123", delta: 2 },
      { label: "Diarrhoeal cases (7d)", value: "42", delta: 1 },
      { label: "OPD respiratory visits", value: "395", delta: 6 },
      { label: "Lab-confirmed dengue", value: "7", delta: 1 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "14", delta: 1 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "25", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "18", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 67,
      rain7d: 29.4, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.21, floodExtent: 0.2,
      ndvi: 0.35, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "ernakulam",
    name: "Ernakulam",
    state: "Kerala",
    lat: 9.98,
    lng: 76.3,
    population: 3300000,
    density: 1072,
    confidence: 71,
    scores: {
      overall: 41, human: 36, animal: 44,
      environment: 35, vector: 47, water: 45,
      respiratory: 66, zoonotic: 39,
    },
    why: [ { factor: "Rainfall (7d: 54.0mm)", value: 11 }, { factor: "Vector breeding conditions", value: 10 }, { factor: "Waterlogging / flood risk", value: 9 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "280", delta: 10 },
      { label: "Diarrhoeal cases (7d)", value: "132", delta: 9 },
      { label: "OPD respiratory visits", value: "398", delta: 6 },
      { label: "Lab-confirmed dengue", value: "18", delta: 8 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "26", delta: 6 },
      { label: "Poultry mortality events", value: "2", delta: 2 },
      { label: "Stray dog bite reports", value: "41", delta: 4 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "90", delta: 9 },
      { label: "Water quality (coliform+)", value: "11% samples", delta: 4 },
      { label: "AQI (PM2.5)", value: "62", delta: 0 },
    ],
    weather: {
      temp: 32, humidity: 76,
      rain7d: 54.0, forecast: "Moderate rain expected; watch for waterlogging",
    },
    satellite: {
      ndwi: 0.29, floodExtent: 0.3,
      ndvi: 0.43, lst: 36,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs", "Issue public advisory on stagnant water and mosquito protection" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    lat: 13.08,
    lng: 80.27,
    population: 7100000,
    density: 26903,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.4mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 12 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "113", delta: 0 },
    ],
    weather: {
      temp: 31, humidity: 54,
      rain7d: 0.4, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.1,
      ndvi: 0.17, lst: 35,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "bengaluru",
    name: "Bengaluru Urban",
    state: "Karnataka",
    lat: 12.97,
    lng: 77.59,
    population: 9600000,
    density: 4381,
    confidence: 69,
    scores: {
      overall: 45, human: 39, animal: 46,
      environment: 44, vector: 51, water: 48,
      respiratory: 34, zoonotic: 42,
    },
    why: [ { factor: "Rainfall (7d: 21.8mm)", value: 12 }, { factor: "Vector breeding conditions", value: 11 }, { factor: "Waterlogging / flood risk", value: 9 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 2 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "302", delta: 11 },
      { label: "Diarrhoeal cases (7d)", value: "140", delta: 9 },
      { label: "OPD respiratory visits", value: "302", delta: 2 },
      { label: "Lab-confirmed dengue", value: "20", delta: 9 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "26", delta: 7 },
      { label: "Poultry mortality events", value: "2", delta: 2 },
      { label: "Stray dog bite reports", value: "43", delta: 4 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "96", delta: 10 },
      { label: "Water quality (coliform+)", value: "12% samples", delta: 4 },
      { label: "AQI (PM2.5)", value: "68", delta: 0 },
    ],
    weather: {
      temp: 31, humidity: 65,
      rain7d: 21.8, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.18, floodExtent: 0.6,
      ndvi: 0.34, lst: 35,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs", "Issue public advisory on stagnant water and mosquito protection" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    lat: 17.39,
    lng: 78.49,
    population: 6800000,
    density: 18172,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.1mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 9 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "96", delta: 0 },
    ],
    weather: {
      temp: 29, humidity: 54,
      rain7d: 0.1, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 33,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "patna",
    name: "Patna",
    state: "Bihar",
    lat: 25.59,
    lng: 85.14,
    population: 5800000,
    density: 1803,
    confidence: 68,
    scores: {
      overall: 22, human: 14, animal: 21,
      environment: 62, vector: 15, water: 15,
      respiratory: 35, zoonotic: 16,
    },
    why: [ { factor: "Rainfall (7d: 29.5mm)", value: 3 }, { factor: "Vector breeding conditions", value: 3 }, { factor: "Waterlogging / flood risk", value: 3 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 }, { factor: "Dengue outbreak record", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "173", delta: 4 },
      { label: "Diarrhoeal cases (7d)", value: "58", delta: 3 },
      { label: "OPD respiratory visits", value: "305", delta: 2 },
      { label: "Lab-confirmed dengue", value: "11", delta: 2 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "16", delta: 2 },
      { label: "Poultry mortality events", value: "1", delta: 0 },
      { label: "Stray dog bite reports", value: "28", delta: 1 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "30", delta: 3 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 1 },
      { label: "AQI (PM2.5)", value: "63", delta: 0 },
    ],
    weather: {
      temp: 25, humidity: 69,
      rain7d: 29.5, forecast: "Partly cloudy, isolated showers likely",
    },
    satellite: {
      ndwi: 0.21, floodExtent: 0.3,
      ndvi: 0.39, lst: 29,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    lat: 26.85,
    lng: 80.95,
    population: 4600000,
    density: 1815,
    confidence: 75,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 74, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.2mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "422", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "63", delta: 0 },
    ],
    weather: {
      temp: 24, humidity: 54,
      rain7d: 0.2, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 28,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    lat: 26.91,
    lng: 75.79,
    population: 6600000,
    density: 598,
    confidence: 76,
    scores: {
      overall: 7, human: 6, animal: 13,
      environment: 10, vector: 5, water: 5,
      respiratory: 75, zoonotic: 8,
    },
    why: [ { factor: "Rainfall (7d: 0.0mm)", value: 1 }, { factor: "Vector breeding conditions", value: 1 }, { factor: "Waterlogging / flood risk", value: 1 }, { factor: "Malaria baseline (1.48/1000)", value: 2 }, { factor: "Population density", value: 1 } ],
    human: [
      { label: "Acute fever reports (7d)", value: "89", delta: 1 },
      { label: "Diarrhoeal cases (7d)", value: "32", delta: 1 },
      { label: "OPD respiratory visits", value: "425", delta: 8 },
      { label: "Lab-confirmed dengue", value: "5", delta: 0 },
    ],
    animal: [
      { label: "Livestock illness reports", value: "13", delta: 0 },
      { label: "Poultry mortality events", value: "0", delta: 0 },
      { label: "Stray dog bite reports", value: "23", delta: 0 },
    ],
    environment: [
      { label: "Stagnant water sites", value: "10", delta: 1 },
      { label: "Water quality (coliform+)", value: "5% samples", delta: 0 },
      { label: "AQI (PM2.5)", value: "61", delta: 0 },
    ],
    weather: {
      temp: 24, humidity: 54,
      rain7d: 0.0, forecast: "Below-normal cumulative rainfall; drought watch active",
    },
    satellite: {
      ndwi: 0.1, floodExtent: 0.0,
      ndvi: 0.17, lst: 28,
    },
    events: [ "Post-monsoon vector breeding peak" ],
    actions: [ "Activate vector source-reduction in waterlogged wards", "Intensify fever and dengue surveillance at PHCs" ],
    dataSource: "IMD Rainfall 08-10-2026",
  },
];

export const getDistrict = (id: string) => districts.find((d) => d.id === id);

export interface TimelinePoint { day: string; score: number; alert?: boolean; note?: string }
export function timeline(d: District): TimelinePoint[] {
  function seed(s: string) {
    let h = 0;
    for (const c of s) h = (h * 31 + c.charCodeAt(0)) >>> 0;
    return () => ((h = (h * 1103515245 + 12345) >>> 0) % 1000) / 1000;
  }
  const r = seed(d.id + 't');
  const pts: TimelinePoint[] = [];
  const start = d.scores.overall - 28;
  for (let i = 0; i < 14; i++) {
    const date = new Date(2026, 9, 9 - 13 + i);
    const score = Math.round(start + (28 * i) / 13 + (r() - 0.5) * 5);
    pts.push({
      day: date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short' }),
      score: i === 13 ? d.scores.overall : score,
    });
  }
  const cross = pts.findIndex((p) => p.score >= 75);
  const cp = pts[cross];
  if (cp) { cp.alert = true; cp.note = 'Threshold crossed — warning issued'; }
  pts[7]!.note = pts[7]!.note ?? 'Rainfall spike detected';
  return pts;
}

export function history(d: District) {
  function seed(s: string) {
    let h = 0;
    for (const c of s) h = (h * 31 + c.charCodeAt(0)) >>> 0;
    return () => ((h = (h * 1103515245 + 12345) >>> 0) % 1000) / 1000;
  }
  const r = seed(d.id + 'h');
  return ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map((m, i) => ({
    month: m,
    avg: Math.round(20 + 50 * Math.max(0, Math.sin((i - 4) / 3)) * (d.scores.overall / 82)),
    current: i <= 9 ? Math.round(20 + 55 * Math.max(0, Math.sin((i - 4) / 3)) * (d.scores.overall / 82) + (r() - 0.5) * 8) : undefined,
  }));
}

export const warnings = districts
  .filter((d) => d.scores.overall >= 55)
  .sort((a, b) => b.scores.overall - a.scores.overall)
  .map((d, i) => ({
    id: `W-2026-${1040 + i}`,
    district: d,
    level: level(d.scores.overall),
    detected: new Date(2026, 9, 9 - i).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
    signals: [...d.why].sort((a, b) => b.value - a.value).slice(0, 3).map((w) => w.factor),
  }));

export const alertHistory = warnings.slice(0, 7).map((w, i) => ({
  date: w.detected,
  district: w.district.name,
  type: w.district.scores.vector > w.district.scores.water ? 'Vector-borne' : 'Water-borne',
  level: w.level,
  status: (i < 2 ? 'Active' : i < 5 ? 'Monitoring' : 'Resolved') as string,
} as { date: string; district: string; type: string; level: Level; status: string }));